### ISSUE TITLE
Bot refuses to set panel api key.

### ISSUE THREAD

**Issue by DeveloperNeon** [FlaringPhoenix/ControlPanel-Bot#2]
Hello! The bot seems to refuse the api key: https://i.vgy.me/uPJHu1.png I am using pterodactyl 1.0. This has worked for MCnodes.co
I have also removed modules/logging.js or whatever its called because, it cant use mkdir.

Ideas?

**Comment by FlaringPhoenix** [comment]
Please make a ticket in BlueFox. I would love to help you out! https://discord.gg/5p78aEpYYz
